name: u3_tarea1
on:
  push:
    branches: [main]
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clona repositorio
        uses: actions/checkout@v3
      - name: Setup environment
        working-directory: tarea0_u2
        run: ./setup.sh
      - name: Lint
        working-directory: tarea0_u2
        run: hugo version
